### PR TITLE
Create message.txt

### PR DESCRIPTION
**Pull request by yuanxun6844**

### CODE REVIEW

**Comment by yuanxun6844** [comment]
Good afternoon from the PRC. I wanted to let you know that a friend of mine named Jack Liao, the CEO of LightningASIC, is an admirer of your work on zogminer(1). He appreciates that you made the program open-source, and is interested in donating in support of its continued development. That is not to mention, he wishes that you may consider employment at LightningASIC, the leading manufacturer of ASIC miners for cryptocurrencies. Thanks for your consideration.

Mr Liao may be reached at lx@lightningasic.com.

**Comment by omaralvarez** [comment]
Which one of us, does this message go out to? Me or nginnever?

**Comment by yuanxun6844** [comment]
Mr Ginnever. Perhaps Mr Liao did not know that zogminer(1) was a collaboration between two people.

**Comment by omaralvarez** [comment]
It is a collaboration between 3 people. @nginnever @omaralvarez and @AgeManning. Check commit history: 

https://github.com/nginnever/zogminer/graphs/contributors

**Comment by yuanxun6844** [comment]
I understand now.

**Pull request closed without merging**
